In [3]:
import numpy as np;
import time;

In [4]:
a = np.zeros(4)
print(f"a= {a} a.shape= {a.shape} a.dtype = {a.dtype}")
a= np.zeros((4,))
print(f"a= {a} a.shape= {a.shape} a.dtype = {a.dtype}")
a=np.random.random_sample(4)
print(f"a= {a} a.shape= {a.shape} a.dtype = {a.dtype}")

a= [0. 0. 0. 0.] a.shape= (4,) a.dtype = float64
a= [0. 0. 0. 0.] a.shape= (4,) a.dtype = float64
a= [0.49920341 0.95895162 0.34216925 0.01161753] a.shape= (4,) a.dtype = float64


In [5]:
a = np.arange(4.)
print(f"a= {a} a.shape= {a.shape} a.dtype = {a.dtype}")
a = np.random.rand(4)
print(f"a= {a} a.shape= {a.shape} a.dtype = {a.dtype}")

a= [0. 1. 2. 3.] a.shape= (4,) a.dtype = float64
a= [0.66705546 0.08697375 0.28116178 0.43999339] a.shape= (4,) a.dtype = float64


In [6]:
a = np.array([1,2,3,4,5])
print(f"a= {a} a.shape= {a.shape} a.dtype = {a.dtype}")
a = np.array([1,2.,3,4,5])
print(f"a= {a} a.shape= {a.shape} a.dtype = {a.dtype}")

a= [1 2 3 4 5] a.shape= (5,) a.dtype = int64
a= [1. 2. 3. 4. 5.] a.shape= (5,) a.dtype = float64


In [7]:
a = np.arange(10)
print(a)
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")
print(f"a[-1] = {a[-1]}")
try:
    c = a[10]
except Exception as e:
    print("Out of index:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
Out of index:
index 10 is out of bounds for axis 0 with size 10


In [8]:
a = np.arange(10)
print(f"a         = {a}")
c = a[2:7:1];     print("a[2:7:1] = ", c)
c = a[2:7:2];     print("a[2:7:2] = ", c)
c = a[3:];        print("a[3:]    = ", c)
c = a[:3];        print("a[:3]    = ", c)
c = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


In [9]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
b = -a 
print(f"b = -a        : {b}")
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")
b = np.mean(a)
print(f"b = np.mean(a): {b}")
b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


In [10]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


In [11]:
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


In [12]:
a = np.array([1, 2, 3, 4])
b = 5 * a 
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


In [13]:
def my_dot(a, b): 
    x=0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


In [15]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")

NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


In [16]:
np.random.seed(1)
a = np.random.rand(10000000)  
b = np.random.rand(10000000)
tic = time.time()  
c = np.dot(a, b)
toc = time.time()
print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")
tic = time.time()
c = my_dot(a,b)
toc = time.time()
print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(toc-tic):.4f} ms ")
del(a);del(b) 

np.dot(a, b) =  2501072.5817
Vectorized version duration: 5.9502 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 1015.3511 ms 


In [19]:
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)
print(f"X[1] has shape {X[1].shape} X[1]={X[1]}")
print(f"w has shape {w.shape} w={w}")
print(f"c has shape {c.shape} c={c}")

X[1] has shape (1,) X[1]=[2]
w has shape (1,) w=[2]
c has shape () c=4


In [20]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.44236513]]


In [21]:
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],
              [4],
              [3]]); 
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


In [26]:
a = np.arange(6).reshape(-1,2)
print(f"a.shape: {a.shape}, \na= {a}")

print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape:   (), a[2,0] = 4,     type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar

a[2].shape:   (2,), a[2]   = [4 5], type(a[2])   = <class 'numpy.ndarray'>


In [ ]:
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")

print("a[1:2,:] = ",a[1:2,:]," a[1:2, :].shape =",a[1:2,:].shape, "a 2-D array")

a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
a[1:2,:] =  [[10 11 12 13 14 15 16 17 18 19]]  a[1:2, :].shape = (1, 10) a 2-D array
